application: expressionizr
version: 1
runtime: php
api_version: 1
threadsafe: yes

handlers:
 - url: /
   script: index.php
 - url: /index\.html
   script: index.php
 - url: /css/*
   static_dir: css 
 - url: /ocr.php
   script: ocr.php
 - url: /extensions
   static_dir: extensions
 - url: /images/(.*\.(gif|png|jpg))
   static_files: images/\1
   upload: images/(.*\.(gif|png|jpg))