application: moechatclient
version: 1
runtime: php
api_version: 1
threadsafe: yes

handlers:
 - url: /
   script: index.html
 - url: /index\.html
   script: index.html
 - url: /css/*
   static_dir: css 
 - url: /js/*
   static_dir: js
 - url: /img/(.*\.(gif|png|jpg))
   static_files: img/\1
   upload: images/(.*\.(gif|png|jpg))